/* eslint-disable @typescript-eslint/no-explicit-any */
"use client";
import { useEffect, useState } from "react";
import { useParams } from "next/navigation";

type Q = any;
export default function QuestionBuilderPage(){const {testId}=useParams<{testId:string}>(); const [questions,setQuestions]=useState<Q[]>([]); const [draft,setDraft]=useState<any>({question_text:"",question_type:"single_choice",is_required:true,weight:1,sort_order:1,is_active:true,options:[{option_text:"",option_value:"",score_value:0,sort_order:1,is_active:true}]});
const load=async()=>{const r=await fetch(`/api/admin/psychometric/tests/${testId}/questions`); const j=await r.json(); setQuestions(j.data||[])}; useEffect(()=>{load()},[testId]);
const save=async()=>{await fetch(`/api/admin/psychometric/tests/${testId}/questions`,{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(draft)}); setDraft({...draft,question_text:""}); load();};
return <div className='space-y-4'><h1 className='text-2xl font-semibold'>Question Builder</h1><div className='grid grid-cols-2 gap-6'><div className='space-y-2'><input className='w-full border rounded p-2' placeholder='Question text' value={draft.question_text} onChange={e=>setDraft({...draft,question_text:e.target.value})}/><select className='w-full border rounded p-2' value={draft.question_type} onChange={e=>setDraft({...draft,question_type:e.target.value})}><option>single_choice</option><option>multiple_choice</option><option>scale</option><option>numeric</option><option>text</option></select><label><input type='checkbox' checked={draft.is_required} onChange={e=>setDraft({...draft,is_required:e.target.checked})}/> Required</label><button onClick={save} className='rounded bg-brand-600 px-3 py-2 text-white'>Add Question</button></div><div className='rounded border p-3'><h2 className='font-medium'>Preview</h2><p>{draft.question_text||'Question preview...'}</p></div></div><div>{questions.sort((a,b)=>(a.sort_order??0)-(b.sort_order??0)).map(q=><div key={q.id} className='rounded border p-3 mb-2'><div className='flex justify-between'><strong>{q.question_text}</strong><div className='space-x-2'><button onClick={async()=>{await fetch(`/api/admin/psychometric/questions/${q.id}/duplicate`,{method:'POST'}); load();}} className='underline text-sm'>Duplicate</button><button onClick={async()=>{await fetch(`/api/admin/psychometric/questions/${q.id}`,{method:'DELETE'}); load();}} className='underline text-sm'>Deactivate</button></div></div><div className='text-xs'>{q.question_type}</div><div>{(q.psychometric_question_options||[]).map((o:any)=><div key={o.id} className='text-sm'>• {o.option_text} ({o.score_value??0})</div>)}</div></div>)}</div></div>
}
