"use client";
import { useState } from "react";
import { StatusBadge } from "@/components/shared/status-badge";

export function AdminInstituteUpdatesClient({ initialUpdates }: { initialUpdates: Array<Record<string, unknown>> }) {
  const [updates, setUpdates] = useState(initialUpdates); const [filter, setFilter] = useState("");
  async function act(id: string, action: string) { const rejectionReason = action === "reject" ? prompt("Enter rejection reason") ?? "" : ""; const res = await fetch(`/api/admin/institute-updates/${id}/moderate`, { method: "PATCH", headers: {"Content-Type":"application/json"}, body: JSON.stringify({ action, rejectionReason })}); if (!res.ok) { alert((await res.json()).error ?? "Failed"); return;} location.reload(); }
  const visible = updates.filter((u)=>!filter || String(u.status)===filter);
  return <div><div className="mb-3"><select className="vi-input" value={filter} onChange={(e)=>setFilter(e.target.value)}><option value="">All</option><option value="pending_review">pending_review</option><option value="approved">approved</option><option value="rejected">rejected</option><option value="hidden">hidden</option><option value="deleted">deleted</option></select></div><div className="space-y-3">{visible.map((u)=><div key={String(u.id)} className="vi-card p-4"><div className="flex justify-between"><p className="text-sm font-medium">{String((u.institutes as {name?: string})?.name ?? "Institute")}</p><StatusBadge status={String(u.status ?? "pending_review")} /></div><p className="mt-2 text-sm">{String(u.content ?? "")}</p>{u.image_url ? <img src={String(u.image_url)} className="mt-2 h-40 w-full rounded object-cover" alt="update"/>:null}{u.video_url ? <video src={String(u.video_url)} controls className="mt-2 h-48 w-full rounded bg-black"/>:null}<div className="mt-3 flex flex-wrap gap-2"><button className="vi-button-secondary" onClick={()=>act(String(u.id),"approve")}>Approve</button><button className="vi-button-secondary" onClick={()=>act(String(u.id),"reject")}>Reject</button><button className="vi-button-secondary" onClick={()=>act(String(u.id),"hide")}>Hide</button><button className="vi-button-secondary" onClick={()=>act(String(u.id),"restore")}>Restore</button><button className="vi-button-secondary" onClick={()=>act(String(u.id),"delete")}>Delete</button></div></div>)}</div></div>
}
