alter table public.courses
  add column if not exists category text,
  add column if not exists subcategory text,
  add column if not exists course_level text,
  add column if not exists language text,
  add column if not exists delivery_mode text,
  add column if not exists duration_value int,
  add column if not exists duration_unit text,
  add column if not exists weekly_schedule text,
  add column if not exists start_date date,
  add column if not exists end_date date,
  add column if not exists eligibility text,
  add column if not exists prerequisites text,
  add column if not exists learning_outcomes text,
  add column if not exists target_audience text,
  add column if not exists syllabus text,
  add column if not exists certificate_available boolean default false,
  add column if not exists certification_details text,
  add column if not exists total_seats int,
  add column if not exists admission_deadline date,
  add column if not exists support_email text,
  add column if not exists support_phone text,
  add column if not exists instructor_name text,
  add column if not exists instructor_qualification text,
  add column if not exists demo_video_url text,
  add column if not exists brochure_url text;
